# Generated by Django 5.0.4 on 2024-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(),
        ),
    ]
