# Generated by Django 5.0.4 on 2024-04-28 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_realtion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtion',
            new_name='Relation',
        ),
    ]
