# Generated by Django 5.0.4 on 2024-04-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_realtion_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
